2018-04-03 10:51:17,984 {__init__:32} ERROR - 192.168.0.193 GET http /api/redirect_latest?
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 87, in redirect_latest
    abort(400)
NameError: name 'abort' is not defined
2018-04-03 10:52:45,809 {__init__:36} ERROR - 192.168.0.193 GET http /api/redirect_latest?ip=192.168.66.38
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 85, in redirect_latest
    return redirect(Zapi().get_link_latest(ip=request.args.get('ip')))
NameError: name 'redirect' is not defined
2018-04-03 10:53:39,551 {__init__:36} ERROR - 192.168.0.193 GET http /api/redirect_latest?ip=192.168.66.38
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 85, in redirect_latest
    return redirect(Zapi().get_link_latest(ip=request.args.get('ip')))
NameError: name 'Zapi' is not defined
2018-04-03 10:57:09,696 {__init__:36} ERROR - 192.168.0.193 GET http /api/redirect_latest?ip=192.168.66.38
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 86, in redirect_latest
    return redirect(Zapi().get_link_latest(ip=request.args.get('ip')))
  File "/home/roman/development/zbxsyncer/app/libs/zapi.py", line 19, in __init__
    self.url = ZABBIX_URL
NameError: name 'ZABBIX_URL' is not defined
2018-04-03 10:59:37,088 {__init__:36} ERROR - 192.168.0.193 GET http /api/redirect_latest?ip=192.168.66.38
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 86, in redirect_latest
    return redirect(Zapi().get_link_latest(ip=request.args.get('ip')))
  File "/home/roman/development/zbxsyncer/app/libs/zapi.py", line 27, in __init__
    self.init_proxy()
  File "/home/roman/development/zbxsyncer/app/libs/zapi.py", line 40, in init_proxy
    output="extend"
  File "/home/roman/development/zbxsyncer/app/libs/zapi.py", line 35, in _do_request
    return format_data(self.conn.do_request(method, params)['result'])
NameError: name 'format_data' is not defined
2018-04-03 11:00:26,889 {zapi:46} DEBUG - proxy 10239 in offline
2018-04-03 11:00:26,889 {zapi:46} DEBUG - proxy 10249 in offline
2018-04-03 11:00:26,889 {zapi:46} DEBUG - proxy 10244 in offline
2018-04-03 11:00:26,890 {zapi:46} DEBUG - proxy 10247 in offline
2018-04-03 11:00:42,204 {zapi:46} DEBUG - proxy 10239 in offline
2018-04-03 11:00:42,204 {zapi:46} DEBUG - proxy 10249 in offline
2018-04-03 11:00:42,204 {zapi:46} DEBUG - proxy 10244 in offline
2018-04-03 11:00:42,204 {zapi:46} DEBUG - proxy 10247 in offline
2018-04-03 11:02:10,405 {__init__:36} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 50, in sync_by_device_id
    timestamp = int(time.time())
NameError: name 'time' is not defined
2018-04-03 11:03:36,853 {__init__:36} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 52, in sync_by_device_id
    if not is_int(request.args.get('device_id')):
NameError: name 'is_int' is not defined
2018-04-03 11:04:58,952 {__init__:36} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 52, in sync_by_device_id
    if not request.args.get('device_id').isnumber():
AttributeError: 'NoneType' object has no attribute 'isnumber'
2018-04-03 11:07:53,183 {__init__:36} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=qwe
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 49, in sync_by_device_id
    if not device_id or not device_id.isnumber():
AttributeError: 'str' object has no attribute 'isnumber'
2018-04-03 11:08:30,616 {__init__:36} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=123
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 58, in sync_by_device_id
    eqm_device = Datapi().GetDataViaOracle(
NameError: name 'Datapi' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 75, in sync_by_device_id
    logging.error(u'{0} {1}'.format(request.args.get('device_id'), repr(e)))
NameError: name 'logging' is not defined
2018-04-03 11:08:52,354 {__init__:36} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 58, in sync_by_device_id
    eqm_device = Datapi().GetDataViaOracle(
NameError: name 'Datapi' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 75, in sync_by_device_id
    logging.error(u'{0} {1}'.format(request.args.get('device_id'), repr(e)))
NameError: name 'logging' is not defined
2018-04-03 11:09:43,696 {__init__:36} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 58, in sync_by_device_id
    eqm_device = Datapi().GetDataViaOracle(
NameError: name 'Datapi' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 75, in sync_by_device_id
    app.logging.error(u'{0} {1}'.format(request.args.get('device_id'), repr(e)))
AttributeError: 'Flask' object has no attribute 'logging'
2018-04-03 11:10:08,213 {api:75} ERROR - 707192 NameError("name 'Datapi' is not defined",)
2018-04-03 11:12:43,276 {api:75} ERROR - 707192 AttributeError("'SQLAlchemy' object has no attribute 'execute'",)
2018-04-03 11:12:55,593 {api:75} ERROR - 707192 NameError("name 'SQL_SELECT_DEVICES' is not defined",)
2018-04-03 11:13:10,777 {api:75} ERROR - 707192 ImportError("No module named 'cx_Oracle'",)
2018-04-03 11:13:37,792 {api:75} ERROR - 707192 DatabaseError('(cx_Oracle.DatabaseError) DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help',)
2018-04-03 11:21:56,565 {api:75} ERROR - 707192 DatabaseError('(cx_Oracle.DatabaseError) DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help',)
2018-04-03 11:27:14,967 {api:75} ERROR - 707192 AttributeError("'ResultProxy' object has no attribute 'empty'",)
2018-04-03 11:27:14,994 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 82, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <sqlalchemy.engine.result.ResultProxy object at 0x7f0b6c0200b8> is not JSON serializable
2018-04-03 11:29:57,600 {api:76} ERROR - 707192 AttributeError("'list' object has no attribute 'empty'",)
2018-04-03 11:29:57,605 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 83, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: (707192, 12593, 'dslam1.bs-5020.msk', '10.77.86.164', 97, '2103', 'engforta', None, None, 'virtual', 15, 11585, 11585, None, 'default') is not JSON serializable
2018-04-03 11:30:59,050 {api:76} ERROR - 707192 AttributeError("'list' object has no attribute 'empty'",)
2018-04-03 11:30:59,053 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 62, in sync_by_device_id
    if eqm_device.empty:
AttributeError: 'list' object has no attribute 'empty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 77, in sync_by_device_id
    error = repr(e)
UnboundLocalError: local variable 'e' referenced before assignment
2018-04-03 11:31:15,924 {api:76} ERROR - 707192 AttributeError("'list' object has no attribute 'empty'",)
2018-04-03 11:31:15,928 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 83, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: (707192, 12593, 'dslam1.bs-5020.msk', '10.77.86.164', 97, '2103', 'engforta', None, None, 'virtual', 15, 11585, 11585, None, 'default') is not JSON serializable
2018-04-03 11:34:09,940 {api:76} ERROR - 707192 AttributeError("'ResultProxy' object has no attribute 'all'",)
2018-04-03 11:34:32,113 {api:76} ERROR - 707192 ValueError('dictionary update sequence element #0 has length 15; 2 is required',)
2018-04-03 11:34:32,117 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 83, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: (707192, 12593, 'dslam1.bs-5020.msk', '10.77.86.164', 97, '2103', 'engforta', None, None, 'virtual', 15, 11585, 11585, None, 'default') is not JSON serializable
2018-04-03 11:37:51,928 {api:76} ERROR - 707192 AttributeError("'ResultProxy' object has no attribute 'empty'",)
2018-04-03 11:37:51,933 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 83, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <sqlalchemy.engine.result.ResultProxy object at 0x7f310f7a60b8> is not JSON serializable
2018-04-03 11:38:48,892 {api:76} ERROR - 707192 AttributeError("Could not locate column in row for column 'empty'",)
2018-04-03 11:38:48,897 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 83, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: (707192, 12593, 'dslam1.bs-5020.msk', '10.77.86.164', 97, '2103', 'engforta', None, None, 'virtual', 15, 11585, 11585, None, 'default') is not JSON serializable
2018-04-03 11:39:42,495 {api:78} ERROR - 707192 AttributeError("'ResultProxy' object has no attribute 'empty'",)
2018-04-03 11:39:42,500 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 85, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <sqlalchemy.engine.result.ResultProxy object at 0x7fdab005b0b8> is not JSON serializable
2018-04-03 11:40:27,853 {api:78} ERROR - 707192 AttributeError("Could not locate column in row for column 'empty'",)
2018-04-03 11:40:27,857 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 85, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: (707192, 12593, 'dslam1.bs-5020.msk', '10.77.86.164', 97, '2103', 'engforta', None, None, 'virtual', 15, 11585, 11585, None, 'default') is not JSON serializable
2018-04-03 11:41:00,728 {api:79} ERROR - 707192 AttributeError("Could not locate column in row for column 'empty'",)
2018-04-03 11:41:00,733 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 86, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: (707192, 12593, 'dslam1.bs-5020.msk', '10.77.86.164', 97, '2103', 'engforta', None, None, 'virtual', 15, 11585, 11585, None, 'default') is not JSON serializable
2018-04-03 11:41:58,052 {api:80} ERROR - 707192 AttributeError("Could not locate column in row for column 'empty'",)
2018-04-03 11:41:58,057 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 87, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: (707192, 12593, 'dslam1.bs-5020.msk', '10.77.86.164', 97, '2103', 'engforta', None, None, 'virtual', 15, 11585, 11585, None, 'default') is not JSON serializable
2018-04-03 11:45:28,781 {api:81} ERROR - 707192 AttributeError("'SQLAlchemy' object has no attribute 'cursor'",)
2018-04-03 11:46:23,837 {api:81} ERROR - 707192 NameError("name 'execute' is not defined",)
2018-04-03 11:46:46,597 {api:81} ERROR - 707192 AttributeError("'SQLAlchemy' object has no attribute 'cursor'",)
2018-04-03 11:48:08,861 {api:81} ERROR - 707192 TypeError("'numpy.ndarray' object is not callable",)
2018-04-03 11:48:08,874 {__init__:39} ERROR - 192.168.0.193 GET http /api/sync_by_device_id?device_id=707192
Traceback (most recent call last):
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roman/development/zbxsyncer/app/blueprints/api.py", line 88, in sync_by_device_id
    timestamp = timestamp
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/roman/development/zbxsyncer/venv/lib/python3.5/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError:      host  device_type         device_name     device_ip  department_id  \
0  707192        12593  dslam1.bs-5020.msk  10.77.86.164             97   

  monitoring_type macro_snmp_community macro_icmp_ping_loss_limit  \
0            2103             engforta                       None   

  macro_icmp_ping_response_limit group_name  zbx_groupid  zbx_master_proxyid  \
0                           None    virtual           15               11585   

   zbx_slave_proxyid zbx_templateids   driver  
0              11585            None  default   is not JSON serializable
2018-04-03 11:51:27,487 {api:69} ERROR - NameError("name 'Publisher' is not defined",)
2018-04-03 11:51:28,161 {zapi:46} DEBUG - proxy 10239 in offline
2018-04-03 11:51:28,161 {zapi:46} DEBUG - proxy 10249 in offline
2018-04-03 11:51:28,162 {zapi:46} DEBUG - proxy 10244 in offline
2018-04-03 11:51:28,162 {zapi:46} DEBUG - proxy 10247 in offline
2018-04-03 11:51:28,314 {api:76} ERROR - 707192 NameError("name 'MONITORING_ICMP' is not defined",)
2018-04-03 12:00:01,758 {zapi:46} DEBUG - proxy 10239 in offline
2018-04-03 12:00:01,759 {zapi:46} DEBUG - proxy 10249 in offline
2018-04-03 12:00:01,759 {zapi:46} DEBUG - proxy 10244 in offline
2018-04-03 12:00:01,760 {zapi:46} DEBUG - proxy 10247 in offline
2018-04-03 12:00:02,201 {api:76} ERROR - 707192 NameError("name 'utf8' is not defined",)
2018-04-03 12:01:41,046 {zapi:46} DEBUG - proxy 10239 in offline
2018-04-03 12:01:41,047 {zapi:46} DEBUG - proxy 10249 in offline
2018-04-03 12:01:41,047 {zapi:46} DEBUG - proxy 10244 in offline
2018-04-03 12:01:41,047 {zapi:46} DEBUG - proxy 10247 in offline
